<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
$status=trim($_GET['status']??'');$keyword=trim($_GET['q']??'');$where=[];$params=[];if($status!==''){$where[]='b.status=?';$params[]=$status;}if($keyword!==''){$where[]='(b.booking_code LIKE ? OR u.name LIKE ? OR p.name LIKE ?)';$like='%'.$keyword.'%';array_push($params,$like,$like,$like);}$sql="SELECT b.*,u.name customer_name,u.phone,p.name package_name FROM bookings b JOIN users u ON u.id=b.user_id JOIN packages p ON p.id=b.package_id".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY b.created_at DESC";$stmt=$pdo->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();
$pageTitle='Data Pemesanan';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="container"><div class="dashboard-head"><div><h1>Data Pemesanan</h1><p>Verifikasi detail acara dan kelola status pesanan pelanggan.</p></div></div><div class="panel"><div class="panel-body"><form class="filter-bar" method="get"><div class="form-group"><label>Pencarian</label><input name="q" value="<?= e($keyword) ?>" placeholder="Kode, pelanggan, atau paket"></div><div class="form-group"><label>Status</label><select name="status"><option value="">Semua status</option><?php foreach(['awaiting_payment','payment_review','confirmed','completed','cancelled'] as $s): ?><option value="<?= e($s) ?>" <?= $status===$s?'selected':'' ?>><?= e(booking_status_label($s)) ?></option><?php endforeach; ?></select></div><button class="btn btn-dark" type="submit">Cari</button><a class="btn btn-outline" href="<?= url('admin/bookings.php') ?>">Reset</a></form></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Kode</th><th>Pelanggan</th><th>Paket</th><th>Acara</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="7" class="empty">Data tidak ditemukan.</td></tr><?php else: foreach($rows as $r): ?><tr><td><strong><?= e($r['booking_code']) ?></strong><br><small><?= date('d-m-Y H:i',strtotime($r['created_at'])) ?></small></td><td><?= e($r['customer_name']) ?><br><small><?= e($r['phone']) ?></small></td><td><?= e($r['package_name']) ?></td><td><?= date('d-m-Y',strtotime($r['event_date'])) ?>, <?= substr($r['start_time'],0,5) ?><br><small><?= e($r['location']) ?></small></td><td><?= rupiah($r['total_price']) ?></td><td><span class="badge badge-<?= status_class($r['status']) ?>"><?= e(booking_status_label($r['status'])) ?></span></td><td><a class="btn btn-outline btn-sm" href="<?= url('admin/booking_detail.php?id='.$r['id']) ?>">Kelola</a></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
