<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
$id=(int)($_GET['id']??$_POST['id']??0);$stmt=$pdo->prepare("SELECT b.*,u.name customer_name,u.email,u.phone,u.address,p.name package_name,p.category,p.duration_hours FROM bookings b JOIN users u ON u.id=b.user_id JOIN packages p ON p.id=b.package_id WHERE b.id=?");$stmt->execute([$id]);$order=$stmt->fetch();if(!$order){flash('danger','Pemesanan tidak ditemukan.');redirect('admin/bookings.php');}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$status=$_POST['status']??'';$note=trim($_POST['admin_note']??'');$allowed=['awaiting_payment','payment_review','confirmed','completed','cancelled'];if(!in_array($status,$allowed,true)){flash('danger','Status tidak valid.');redirect('admin/booking_detail.php?id='.$id);}try{$pdo->beginTransaction();$stmt=$pdo->prepare("UPDATE bookings SET status=?,admin_note=? WHERE id=?");$stmt->execute([$status,$note,$id]);if($status==='confirmed'){$start=new DateTime($order['event_date'].' '.$order['start_time']);$end=(clone $start)->modify('+'.(float)$order['duration_hours'].' hours');$stmt=$pdo->prepare("INSERT INTO schedules(booking_id,event_date,start_time,end_time,notes,status) VALUES(?,?,?,?,?,'scheduled') ON DUPLICATE KEY UPDATE event_date=VALUES(event_date),start_time=VALUES(start_time),end_time=VALUES(end_time),notes=VALUES(notes),status='scheduled'");$stmt->execute([$id,$order['event_date'],$order['start_time'],$end->format('H:i:s'),'Jadwal '.$order['package_name'].' - '.$order['customer_name']]);}elseif($status==='completed'){$stmt=$pdo->prepare("UPDATE schedules SET status='completed' WHERE booking_id=?");$stmt->execute([$id]);}elseif($status==='cancelled'){$stmt=$pdo->prepare("UPDATE schedules SET status='cancelled' WHERE booking_id=?");$stmt->execute([$id]);}$pdo->commit();flash('success','Status pemesanan berhasil diperbarui.');redirect('admin/booking_detail.php?id='.$id);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('danger','Gagal memperbarui status: '.$e->getMessage());redirect('admin/booking_detail.php?id='.$id);}}
$stmt=$pdo->prepare("SELECT * FROM payments WHERE booking_id=? ORDER BY id DESC");$stmt->execute([$id]);$payments=$stmt->fetchAll();$pageTitle='Detail Pemesanan';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="container"><div class="dashboard-head"><div><h1><?= e($order['booking_code']) ?></h1><p>Kelola detail pemesanan dan jadwal.</p></div><a class="btn btn-outline" href="<?= url('admin/bookings.php') ?>">← Kembali</a></div><div class="detail-grid"><div><div class="panel"><div class="panel-head"><h2>Informasi Pemesanan</h2><span class="badge badge-<?= status_class($order['status']) ?>"><?= e(booking_status_label($order['status'])) ?></span></div><div class="panel-body"><dl class="detail-list"><dt>Pelanggan</dt><dd><?= e($order['customer_name']) ?></dd><dt>Kontak</dt><dd><?= e($order['phone']) ?> / <?= e($order['email']) ?></dd><dt>Paket</dt><dd><?= e($order['package_name']) ?> — <?= e($order['category']) ?></dd><dt>Tanggal</dt><dd><?= date('d F Y',strtotime($order['event_date'])) ?>, <?= substr($order['start_time'],0,5) ?> WIB</dd><dt>Lokasi</dt><dd><?= e($order['location']) ?></dd><dt>Harga / DP</dt><dd><?= rupiah($order['total_price']) ?> / <?= rupiah($order['dp_amount']) ?></dd><dt>Catatan pelanggan</dt><dd><?= nl2br(e($order['notes']?:'-')) ?></dd></dl></div></div><div class="panel"><div class="panel-head"><h2>Pembayaran</h2><a class="btn btn-outline btn-sm" href="<?= url('admin/payments.php') ?>">Kelola Pembayaran</a></div><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Jumlah</th><th>Pengirim</th><th>Status</th><th>Bukti</th></tr></thead><tbody><?php if(!$payments): ?><tr><td colspan="5" class="empty">Belum ada pembayaran.</td></tr><?php else: foreach($payments as $p): ?><tr><td><?= date('d-m-Y',strtotime($p['payment_date'])) ?></td><td><?= rupiah($p['amount']) ?></td><td><?= e($p['bank_name']) ?><br><small><?= e($p['account_name']) ?></small></td><td><span class="badge badge-<?= status_class($p['verification_status']) ?>"><?= e(payment_status_label($p['verification_status'])) ?></span></td><td><a class="btn btn-outline btn-sm" target="_blank" href="<?= url('uploads/payments/'.$p['proof']) ?>">Lihat</a></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div><aside><div class="form-card"><h3 style="margin-top:0">Perbarui Status</h3><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= $id ?>"><div class="form-group"><label>Status Pemesanan</label><select name="status"><?php foreach(['awaiting_payment','payment_review','confirmed','completed','cancelled'] as $s): ?><option value="<?= e($s) ?>" <?= $order['status']===$s?'selected':'' ?>><?= e(booking_status_label($s)) ?></option><?php endforeach; ?></select></div><div class="form-group" style="margin-top:14px"><label>Catatan Admin</label><textarea name="admin_note"><?= e($order['admin_note']) ?></textarea></div><button class="btn btn-primary btn-block" style="margin-top:18px" type="submit">Simpan Status</button></form></div></aside></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
