<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=(int)($_POST['id']??0);$status=($_POST['status']??'inactive')==='active'?'active':'inactive';$stmt=$pdo->prepare("UPDATE users SET status=? WHERE id=? AND role='customer'");$stmt->execute([$status,$id]);flash('success','Status pelanggan diperbarui.');redirect('admin/customers.php');}
$rows=$pdo->query("SELECT u.*,(SELECT COUNT(*) FROM bookings b WHERE b.user_id=u.id) booking_count FROM users u WHERE role='customer' ORDER BY u.created_at DESC")->fetchAll();$pageTitle='Data Pelanggan';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="container"><div class="dashboard-head"><div><h1>Data Pelanggan</h1><p>Daftar akun pelanggan dan jumlah pemesanannya.</p></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Kontak</th><th>Alamat</th><th>Pesanan</th><th>Terdaftar</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="7" class="empty">Belum ada pelanggan.</td></tr><?php else: foreach($rows as $r): ?><tr><td><strong><?= e($r['name']) ?></strong></td><td><?= e($r['email']) ?><br><small><?= e($r['phone']) ?></small></td><td><?= e($r['address']) ?></td><td><?= (int)$r['booking_count'] ?></td><td><?= date('d-m-Y',strtotime($r['created_at'])) ?></td><td><span class="badge badge-<?= status_class($r['status']) ?>"><?= e(ucfirst($r['status'])) ?></span></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="status" value="<?= $r['status']==='active'?'inactive':'active' ?>"><button class="btn <?= $r['status']==='active'?'btn-danger':'btn-success' ?> btn-sm" data-confirm="Ubah status akun pelanggan?" type="submit"><?= $r['status']==='active'?'Nonaktifkan':'Aktifkan' ?></button></form></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
