<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
$id=(int)($_GET['id']??$_POST['id']??0);$item=['title'=>'','category'=>'','description'=>'','photo'=>null,'status'=>'active'];if($id){$stmt=$pdo->prepare("SELECT * FROM gallery WHERE id=?");$stmt->execute([$id]);$found=$stmt->fetch();if(!$found){flash('danger','Data galeri tidak ditemukan.');redirect('admin/gallery.php');}$item=$found;}$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$title=trim($_POST['title']??'');$category=trim($_POST['category']??'');$description=trim($_POST['description']??'');$status=($_POST['status']??'active')==='inactive'?'inactive':'active';if($title===''||$category==='')throw new RuntimeException('Judul dan kategori wajib diisi.');$photo=$item['photo'];if(!empty($_FILES['photo']['name'])){$new=upload_image($_FILES['photo'],'gallery');delete_upload($photo,'gallery');$photo=$new;}if(!$id&& !$photo)throw new RuntimeException('Foto wajib dipilih untuk data galeri baru.');if($id){$stmt=$pdo->prepare("UPDATE gallery SET title=?,category=?,description=?,photo=?,status=? WHERE id=?");$stmt->execute([$title,$category,$description,$photo,$status,$id]);}else{$stmt=$pdo->prepare("INSERT INTO gallery(title,category,description,photo,status) VALUES(?,?,?,?,?)");$stmt->execute([$title,$category,$description,$photo,$status]);}flash('success','Data galeri berhasil disimpan.');redirect('admin/gallery.php');}catch(Throwable $e){$error=$e->getMessage();$item=array_merge($item,$_POST);}}
$pageTitle=$id?'Edit Galeri':'Tambah Galeri';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="narrow"><div class="dashboard-head"><div><h1><?= $id?'Edit':'Tambah' ?> Galeri</h1><p>Tambahkan hasil karya terbaik ke portofolio.</p></div><a class="btn btn-outline" href="<?= url('admin/gallery.php') ?>">← Kembali</a></div><div class="form-card"><?php if($error): ?><div class="form-error"><?= e($error) ?></div><?php endif; ?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= $id ?>"><div class="form-grid"><div class="form-group full"><label>Judul</label><input name="title" value="<?= e((string)$item['title']) ?>" required></div><div class="form-group"><label>Kategori</label><input name="category" value="<?= e((string)$item['category']) ?>" required></div><div class="form-group"><label>Status</label><select name="status"><option value="active" <?= $item['status']==='active'?'selected':'' ?>>Aktif</option><option value="inactive" <?= $item['status']==='inactive'?'selected':'' ?>>Tidak Aktif</option></select></div><div class="form-group full"><label>Deskripsi</label><textarea name="description"><?= e((string)$item['description']) ?></textarea></div><div class="form-group full"><label>Foto</label><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" data-preview="#gallery-preview" <?= $id?'':'required' ?>><span class="help">JPG, PNG, atau WEBP. Maksimal 3 MB.</span><img id="gallery-preview" class="preview" src="<?= $item['photo']?url('uploads/gallery/'.$item['photo']):asset('img/default-gallery.svg') ?>" alt="Pratinjau"></div></div><button class="btn btn-primary btn-block" style="margin-top:20px" type="submit">Simpan Galeri</button></form></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
