<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['delete_id'])){verify_csrf();$id=(int)$_POST['delete_id'];$stmt=$pdo->prepare("SELECT photo FROM gallery WHERE id=?");$stmt->execute([$id]);$row=$stmt->fetch();$stmt=$pdo->prepare("DELETE FROM gallery WHERE id=?");$stmt->execute([$id]);if($row)delete_upload($row['photo'],'gallery');flash('success','Galeri berhasil dihapus.');redirect('admin/gallery.php');}
$rows=$pdo->query("SELECT * FROM gallery ORDER BY id DESC")->fetchAll();$pageTitle='Kelola Galeri';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="container"><div class="dashboard-head"><div><h1>Galeri Portofolio</h1><p>Kelola foto karya yang tampil pada halaman publik.</p></div><a class="btn btn-primary" href="<?= url('admin/gallery_form.php') ?>">+ Tambah Foto</a></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Foto</th><th>Judul</th><th>Kategori</th><th>Deskripsi</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="6" class="empty">Belum ada data galeri.</td></tr><?php else: foreach($rows as $r): ?><tr><td><img src="<?= $r['photo']?url('uploads/gallery/'.$r['photo']):asset('img/default-gallery.svg') ?>" alt="" style="width:72px;height:60px;object-fit:cover;border-radius:8px"></td><td><strong><?= e($r['title']) ?></strong></td><td><?= e($r['category']) ?></td><td><?= e($r['description']) ?></td><td><span class="badge badge-<?= status_class($r['status']) ?>"><?= e(ucfirst($r['status'])) ?></span></td><td><div class="table-actions"><a class="btn btn-outline btn-sm" href="<?= url('admin/gallery_form.php?id='.$r['id']) ?>">Edit</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="delete_id" value="<?= (int)$r['id'] ?>"><button class="btn btn-danger btn-sm" data-confirm="Hapus foto galeri ini?" type="submit">Hapus</button></form></div></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
