<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
$id=(int)($_GET['id']??$_POST['id']??0);$package=['name'=>'','category'=>'','price'=>'','dp_percentage'=>30,'duration_hours'=>2,'description'=>'','features'=>'','photo'=>null,'status'=>'active'];
if($id){$stmt=$pdo->prepare("SELECT * FROM packages WHERE id=?");$stmt->execute([$id]);$found=$stmt->fetch();if(!$found){flash('danger','Paket tidak ditemukan.');redirect('admin/packages.php');}$package=$found;}
$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$data=['name'=>trim($_POST['name']??''),'category'=>trim($_POST['category']??''),'price'=>(float)($_POST['price']??0),'dp_percentage'=>(int)($_POST['dp_percentage']??30),'duration_hours'=>(float)($_POST['duration_hours']??0),'description'=>trim($_POST['description']??''),'features'=>trim($_POST['features']??''),'status'=>($_POST['status']??'active')==='inactive'?'inactive':'active'];if($data['name']===''||$data['category']===''||$data['price']<=0||$data['duration_hours']<=0||$data['description']==='')throw new RuntimeException('Data utama paket wajib diisi dengan benar.');$photo=$package['photo'];if(!empty($_FILES['photo']['name'])){$new=upload_image($_FILES['photo'],'packages');delete_upload($photo,'packages');$photo=$new;}if($id){$stmt=$pdo->prepare("UPDATE packages SET name=?,category=?,price=?,dp_percentage=?,duration_hours=?,description=?,features=?,photo=?,status=? WHERE id=?");$stmt->execute([$data['name'],$data['category'],$data['price'],$data['dp_percentage'],$data['duration_hours'],$data['description'],$data['features'],$photo,$data['status'],$id]);}else{$stmt=$pdo->prepare("INSERT INTO packages(name,category,price,dp_percentage,duration_hours,description,features,photo,status) VALUES(?,?,?,?,?,?,?,?,?)");$stmt->execute([$data['name'],$data['category'],$data['price'],$data['dp_percentage'],$data['duration_hours'],$data['description'],$data['features'],$photo,$data['status']]);}flash('success','Data paket berhasil disimpan.');redirect('admin/packages.php');}catch(Throwable $e){$error=$e->getMessage();$package=array_merge($package,$_POST);}}
$pageTitle=$id?'Edit Paket':'Tambah Paket';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="narrow"><div class="dashboard-head"><div><h1><?= $id?'Edit':'Tambah' ?> Paket</h1><p>Lengkapi informasi paket layanan fotografi.</p></div><a class="btn btn-outline" href="<?= url('admin/packages.php') ?>">← Kembali</a></div><div class="form-card"><?php if($error): ?><div class="form-error"><?= e($error) ?></div><?php endif; ?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= $id ?>"><div class="form-grid"><div class="form-group full"><label>Nama Paket</label><input name="name" value="<?= e((string)$package['name']) ?>" required></div><div class="form-group"><label>Kategori</label><input name="category" value="<?= e((string)$package['category']) ?>" placeholder="Wedding / Wisuda / Produk" required></div><div class="form-group"><label>Harga</label><input type="number" name="price" min="1" value="<?= e((string)$package['price']) ?>" required></div><div class="form-group"><label>DP (%)</label><input type="number" name="dp_percentage" min="0" max="100" value="<?= e((string)$package['dp_percentage']) ?>" required></div><div class="form-group"><label>Durasi (jam)</label><input type="number" name="duration_hours" min="0.5" step="0.5" value="<?= e((string)$package['duration_hours']) ?>" required></div><div class="form-group full"><label>Deskripsi</label><textarea name="description" required><?= e((string)$package['description']) ?></textarea></div><div class="form-group full"><label>Fasilitas Paket</label><textarea name="features" placeholder="Satu fasilitas per baris"><?= e((string)$package['features']) ?></textarea></div><div class="form-group"><label>Status</label><select name="status"><option value="active" <?= $package['status']==='active'?'selected':'' ?>>Aktif</option><option value="inactive" <?= $package['status']==='inactive'?'selected':'' ?>>Tidak Aktif</option></select></div><div class="form-group"><label>Foto Paket</label><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" data-preview="#package-preview"><span class="help">Kosongkan bila tidak mengganti foto.</span></div><div class="form-group full"><img id="package-preview" class="preview" src="<?= $package['photo']?url('uploads/packages/'.$package['photo']):asset('img/default-package.svg') ?>" alt="Pratinjau"></div></div><button class="btn btn-primary btn-block" style="margin-top:20px" type="submit">Simpan Paket</button></form></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
