<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['delete_id'])){verify_csrf();$id=(int)$_POST['delete_id'];$stmt=$pdo->prepare("SELECT photo FROM packages WHERE id=?");$stmt->execute([$id]);$row=$stmt->fetch();try{$stmt=$pdo->prepare("DELETE FROM packages WHERE id=?");$stmt->execute([$id]);if($row)delete_upload($row['photo'],'packages');flash('success','Paket berhasil dihapus.');}catch(PDOException $e){flash('danger','Paket tidak dapat dihapus karena sudah digunakan pada pemesanan. Nonaktifkan paket sebagai gantinya.');}redirect('admin/packages.php');}
$rows=$pdo->query("SELECT p.*,(SELECT COUNT(*) FROM bookings b WHERE b.package_id=p.id) booking_count FROM packages p ORDER BY p.id DESC")->fetchAll();
$pageTitle='Kelola Paket';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="container"><div class="dashboard-head"><div><h1>Data Paket</h1><p>Kelola layanan, harga, DP, durasi, dan foto paket.</p></div><a class="btn btn-primary" href="<?= url('admin/package_form.php') ?>">+ Tambah Paket</a></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Foto</th><th>Nama Paket</th><th>Kategori</th><th>Harga</th><th>DP</th><th>Pesanan</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="8" class="empty">Belum ada paket.</td></tr><?php else: foreach($rows as $r): ?><tr><td><img src="<?= $r['photo']?url('uploads/packages/'.$r['photo']):asset('img/default-package.svg') ?>" alt="" style="width:72px;height:48px;object-fit:cover;border-radius:8px"></td><td><strong><?= e($r['name']) ?></strong><br><small><?= e((string)$r['duration_hours']) ?> jam</small></td><td><?= e($r['category']) ?></td><td><?= rupiah($r['price']) ?></td><td><?= (int)$r['dp_percentage'] ?>%</td><td><?= (int)$r['booking_count'] ?></td><td><span class="badge badge-<?= status_class($r['status']) ?>"><?= e(ucfirst($r['status'])) ?></span></td><td><div class="table-actions"><a class="btn btn-outline btn-sm" href="<?= url('admin/package_form.php?id='.$r['id']) ?>">Edit</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="delete_id" value="<?= (int)$r['id'] ?>"><button class="btn btn-danger btn-sm" data-confirm="Hapus paket ini?" type="submit">Hapus</button></form></div></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
