<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-t');$status=$_GET['status']??'';$where=['b.event_date BETWEEN ? AND ?'];$params=[$from,$to];if($status!==''){$where[]='b.status=?';$params[]=$status;}$sql="SELECT b.*,u.name customer_name,p.name package_name,COALESCE((SELECT SUM(py.amount) FROM payments py WHERE py.booking_id=b.id AND py.verification_status='verified'),0) paid_amount FROM bookings b JOIN users u ON u.id=b.user_id JOIN packages p ON p.id=b.package_id WHERE ".implode(' AND ',$where)." ORDER BY b.event_date";$stmt=$pdo->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();$totalBookings=count($rows);$totalValue=array_sum(array_map(fn($r)=>(float)$r['total_price'],$rows));$totalPaid=array_sum(array_map(fn($r)=>(float)$r['paid_amount'],$rows));
$pageTitle='Laporan Pemesanan';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="container"><div class="dashboard-head"><div><h1>Laporan Pemesanan</h1><p>Rekap berdasarkan periode tanggal acara dan status.</p></div><button class="btn btn-primary no-print" onclick="window.print()">Cetak Laporan</button></div><div class="panel no-print"><div class="panel-body"><form class="filter-bar" method="get"><div class="form-group"><label>Dari</label><input type="date" name="from" value="<?= e($from) ?>"></div><div class="form-group"><label>Sampai</label><input type="date" name="to" value="<?= e($to) ?>"></div><div class="form-group"><label>Status</label><select name="status"><option value="">Semua</option><?php foreach(['awaiting_payment','payment_review','confirmed','completed','cancelled'] as $s): ?><option value="<?= e($s) ?>" <?= $status===$s?'selected':'' ?>><?= e(booking_status_label($s)) ?></option><?php endforeach; ?></select></div><button class="btn btn-dark" type="submit">Tampilkan</button></form></div></div><div class="print-only" style="text-align:center;margin-bottom:25px"><h2>Dua Belas Production</h2><h3>Laporan Pemesanan Jasa Fotografi</h3><p>Periode <?= date('d-m-Y',strtotime($from)) ?> s.d. <?= date('d-m-Y',strtotime($to)) ?></p></div><div class="metric-grid"><div class="metric"><span>Jumlah Pemesanan</span><strong><?= $totalBookings ?></strong></div><div class="metric"><span>Nilai Pemesanan</span><strong style="font-size:1.15rem"><?= rupiah($totalValue) ?></strong></div><div class="metric"><span>Pembayaran Terverifikasi</span><strong style="font-size:1.15rem"><?= rupiah($totalPaid) ?></strong></div><div class="metric"><span>Periode</span><strong style="font-size:1rem"><?= date('d/m/y',strtotime($from)) ?>–<?= date('d/m/y',strtotime($to)) ?></strong></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>No</th><th>Kode</th><th>Pelanggan</th><th>Paket</th><th>Tanggal/Tempat</th><th>Total</th><th>Terbayar</th><th>Status</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="8" class="empty">Tidak ada data pada periode ini.</td></tr><?php else: foreach($rows as $i=>$r): ?><tr><td><?= $i+1 ?></td><td><?= e($r['booking_code']) ?></td><td><?= e($r['customer_name']) ?></td><td><?= e($r['package_name']) ?></td><td><?= date('d-m-Y',strtotime($r['event_date'])) ?><br><small><?= e($r['location']) ?></small></td><td><?= rupiah($r['total_price']) ?></td><td><?= rupiah($r['paid_amount']) ?></td><td><?= e(booking_status_label($r['status'])) ?></td></tr><?php endforeach; endif; ?></tbody><tfoot><tr><th colspan="5">TOTAL</th><th><?= rupiah($totalValue) ?></th><th><?= rupiah($totalPaid) ?></th><th></th></tr></tfoot></table></div></div><div class="print-only" style="width:280px;margin:50px 0 0 auto;text-align:center"><p>Pasaman Barat, <?= date('d F Y') ?></p><br><br><br><p><strong>Administrator</strong></p></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
