<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('admin');
$month=$_GET['month']??date('Y-m');if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');$start=$month.'-01';$end=date('Y-m-t',strtotime($start));$stmt=$pdo->prepare("SELECT s.*,b.booking_code,b.location,u.name customer_name,u.phone,p.name package_name FROM schedules s JOIN bookings b ON b.id=s.booking_id JOIN users u ON u.id=b.user_id JOIN packages p ON p.id=b.package_id WHERE s.event_date BETWEEN ? AND ? ORDER BY s.event_date,s.start_time");$stmt->execute([$start,$end]);$rows=$stmt->fetchAll();
$pageTitle='Jadwal Fotografi';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/admin_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="container"><div class="dashboard-head"><div><h1>Jadwal Fotografi</h1><p>Jadwal terbentuk otomatis setelah pembayaran diverifikasi.</p></div></div><div class="panel"><div class="panel-body"><form class="filter-bar" method="get"><div class="form-group"><label>Bulan</label><input type="month" name="month" value="<?= e($month) ?>"></div><button class="btn btn-dark" type="submit">Tampilkan</button></form></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Waktu</th><th>Kode</th><th>Pelanggan</th><th>Paket</th><th>Lokasi</th><th>Status</th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="7" class="empty">Belum ada jadwal pada bulan ini.</td></tr><?php else: foreach($rows as $r): ?><tr><td><strong><?= date('d F Y',strtotime($r['event_date'])) ?></strong></td><td><?= substr($r['start_time'],0,5) ?> - <?= $r['end_time']?substr($r['end_time'],0,5):'-' ?></td><td><a href="<?= url('admin/booking_detail.php?id='.$r['booking_id']) ?>"><?= e($r['booking_code']) ?></a></td><td><?= e($r['customer_name']) ?><br><small><?= e($r['phone']) ?></small></td><td><?= e($r['package_name']) ?></td><td><?= e($r['location']) ?></td><td><span class="badge badge-<?= status_class($r['status']==='scheduled'?'confirmed':$r['status']) ?>"><?= e(ucfirst($r['status'])) ?></span></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
