<?php

declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/auth.php';require_role('customer');
$id=(int)($_GET['booking']??$_POST['booking_id']??0);$stmt=$pdo->prepare("SELECT b.*,p.name package_name FROM bookings b JOIN packages p ON p.id=b.package_id WHERE b.id=? AND b.user_id=?");$stmt->execute([$id,current_user()['id']]);$order=$stmt->fetch();if(!$order){flash('danger','Pesanan tidak ditemukan.');redirect('customer/orders.php');}
$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{$amount=(float)($_POST['amount']??0);$date=$_POST['payment_date']??'';$bank=trim($_POST['bank_name']??'');$account=trim($_POST['account_name']??'');if($amount<=0||!$date||$bank===''||$account==='')throw new RuntimeException('Semua data pembayaran wajib diisi.');$proof=upload_image($_FILES['proof']??[],'payments');$pdo->beginTransaction();$stmt=$pdo->prepare("INSERT INTO payments(booking_id,payment_date,amount,bank_name,account_name,proof) VALUES(?,?,?,?,?,?)");$stmt->execute([$id,$date,$amount,$bank,$account,$proof]);$stmt=$pdo->prepare("UPDATE bookings SET status='payment_review' WHERE id=?");$stmt->execute([$id]);$pdo->commit();flash('success','Bukti pembayaran berhasil dikirim dan menunggu verifikasi admin.');redirect('customer/order_detail.php?id='.$id);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}}
$pageTitle='Unggah Pembayaran';require __DIR__.'/../includes/header.php';require __DIR__.'/../includes/customer_nav.php';
?>
<section class="section" style="padding-top:30px"><div class="narrow"><div class="dashboard-head"><div><h1>Unggah Pembayaran</h1><p><?= e($order['booking_code']) ?> — <?= e($order['package_name']) ?></p></div></div><div class="form-card"><?php if($error): ?><div class="form-error"><?= e($error) ?></div><?php endif; ?><div class="demo-box"><strong>Nominal DP yang disarankan:</strong> <?= rupiah($order['dp_amount']) ?><br>Rekening tujuan dapat disesuaikan oleh admin pada informasi studio.</div><form method="post" enctype="multipart/form-data" style="margin-top:20px"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="booking_id" value="<?= (int)$id ?>"><div class="form-grid"><div class="form-group"><label>Tanggal Bayar</label><input type="date" name="payment_date" value="<?= old('payment_date',date('Y-m-d')) ?>" required></div><div class="form-group"><label>Jumlah Bayar</label><input type="number" name="amount" min="1" value="<?= old('amount',(string)(int)$order['dp_amount']) ?>" required></div><div class="form-group"><label>Bank / E-Wallet Pengirim</label><input name="bank_name" value="<?= old('bank_name') ?>" required></div><div class="form-group"><label>Nama Pemilik Rekening</label><input name="account_name" value="<?= old('account_name') ?>" required></div><div class="form-group full"><label>Bukti Pembayaran</label><input type="file" name="proof" accept="image/jpeg,image/png,image/webp" data-preview="#proof-preview" required><span class="help">JPG, PNG, atau WEBP. Maksimal 3 MB.</span><img id="proof-preview" class="preview" hidden alt="Pratinjau bukti"></div></div><button class="btn btn-primary btn-block" style="margin-top:20px" type="submit">Kirim Bukti Pembayaran</button></form></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
